"""
ShadowGate - API Hashing Module
Implements multiple hash algorithms for string hiding
"""

import struct
from typing import Dict, List, Tuple

# ============================================================================
# Hash Algorithms
# ============================================================================

class HashEngine:
    """API name hashing engine"""
    
    # DJB2 seed (from HookChain)
    DJB2_SEED = 0x7734773477347734
    
    @staticmethod
    def djb2(data: bytes, seed: int = None) -> int:
        """
        DJB2 hash algorithm (64-bit)
        Used by HookChain for API resolution
        """
        if seed is None:
            seed = HashEngine.DJB2_SEED
        
        hash_value = seed
        
        for byte in data:
            hash_value = ((hash_value << 5) + hash_value) + byte
            hash_value &= 0xFFFFFFFFFFFFFFFF  # Keep 64-bit
        
        return hash_value
    
    @staticmethod
    def djb2_32(data: bytes) -> int:
        """DJB2 hash algorithm (32-bit version)"""
        hash_value = 5381
        
        for byte in data:
            hash_value = ((hash_value << 5) + hash_value) + byte
            hash_value &= 0xFFFFFFFF  # Keep 32-bit
        
        return hash_value
    
    @staticmethod
    def crc32(data: bytes) -> int:
        """CRC32 hash"""
        import zlib
        return zlib.crc32(data) & 0xFFFFFFFF
    
    @staticmethod
    def fnv1a_64(data: bytes) -> int:
        """FNV-1a hash algorithm (64-bit)"""
        FNV_OFFSET = 0xcbf29ce484222325
        FNV_PRIME = 0x100000001b3
        
        hash_value = FNV_OFFSET
        
        for byte in data:
            hash_value ^= byte
            hash_value = (hash_value * FNV_PRIME) & 0xFFFFFFFFFFFFFFFF
        
        return hash_value
    
    @staticmethod
    def xor_hash(data: bytes, key: int = 0x5A) -> int:
        """Simple XOR-based hash (32-bit)"""
        hash_value = 0
        
        for i, byte in enumerate(data):
            hash_value ^= (byte ^ key) << ((i % 4) * 8)
            hash_value = ((hash_value << 7) | (hash_value >> 25)) & 0xFFFFFFFF
        
        return hash_value
    
    @classmethod
    def hash_api_name(cls, name: str, algorithm: str = "djb2", skip_prefix: int = 0) -> int:
        """
        Hash an API name
        
        Args:
            name: API function name (e.g., "NtAllocateVirtualMemory")
            algorithm: Hash algorithm to use
            skip_prefix: Number of characters to skip (e.g., 2 for "Nt"/"Zw")
        """
        # Convert to bytes and optionally skip prefix
        data = name[skip_prefix:].encode('ascii')
        
        if algorithm == "djb2":
            return cls.djb2(data)
        elif algorithm == "djb2_32":
            return cls.djb2_32(data)
        elif algorithm == "crc32":
            return cls.crc32(data)
        elif algorithm == "fnv1a":
            return cls.fnv1a_64(data)
        elif algorithm == "xor":
            return cls.xor_hash(data)
        else:
            raise ValueError(f"Unknown algorithm: {algorithm}")
    
    @classmethod
    def generate_hash_table(cls, api_names: List[str], algorithm: str = "djb2", 
                           skip_prefix: int = 2) -> Dict[str, int]:
        """Generate hash table for list of API names"""
        table = {}
        for name in api_names:
            hash_value = cls.hash_api_name(name, algorithm, skip_prefix)
            table[name] = hash_value
        return table
    
    @classmethod
    def generate_cpp_defines(cls, api_names: List[str], algorithm: str = "djb2",
                            skip_prefix: int = 2) -> str:
        """Generate C++ #define statements for API hashes"""
        lines = []
        lines.append(f"// API Hashes (Algorithm: {algorithm.upper()})")
        lines.append(f"// Auto-generated by ShadowGate Builder\n")
        
        for name in api_names:
            hash_value = cls.hash_api_name(name, algorithm, skip_prefix)
            # Create define name: NtAllocateVirtualMemory -> HASH_NtAllocateVirtualMemory
            define_name = f"HASH_{name}"
            lines.append(f"#define {define_name:<45} 0x{hash_value:016X}ULL")
        
        return '\n'.join(lines)
    
    @classmethod
    def generate_cpp_hash_function(cls, algorithm: str = "djb2") -> str:
        """Generate C++ hash function code"""
        
        if algorithm == "djb2":
            return '''
// DJB2 Hash Function (64-bit)
__forceinline DWORD64 HashString(LPCSTR str) {
    DWORD64 hash = 0x7734773477347734ULL;
    while (*str) {
        hash = ((hash << 5) + hash) + (DWORD64)*str++;
    }
    return hash;
}

// Hash with prefix skip (for Nt/Zw functions)
__forceinline DWORD64 HashApi(LPCSTR name, DWORD skip) {
    return HashString(name + skip);
}
'''
        elif algorithm == "fnv1a":
            return '''
// FNV-1a Hash Function (64-bit)
__forceinline DWORD64 HashString(LPCSTR str) {
    DWORD64 hash = 0xcbf29ce484222325ULL;
    const DWORD64 prime = 0x100000001b3ULL;
    while (*str) {
        hash ^= (DWORD64)*str++;
        hash *= prime;
    }
    return hash;
}

// Hash with prefix skip
__forceinline DWORD64 HashApi(LPCSTR name, DWORD skip) {
    return HashString(name + skip);
}
'''
        elif algorithm == "crc32":
            return '''
// CRC32 Hash Function
static const DWORD crc32_table[256] = {
    0x00000000, 0x77073096, 0xEE0E612C, 0x990951BA, 0x076DC419, 0x706AF48F, 0xE963A535, 0x9E6495A3,
    0x0EDB8832, 0x79DCB8A4, 0xE0D5E91E, 0x97D2D988, 0x09B64C2B, 0x7EB17CBD, 0xE7B82D07, 0x90BF1D91,
    0x1DB71064, 0x6AB020F2, 0xF3B97148, 0x84BE41DE, 0x1ADAD47D, 0x6DDDE4EB, 0xF4D4B551, 0x83D385C7,
    0x136C9856, 0x646BA8C0, 0xFD62F97A, 0x8A65C9EC, 0x14015C4F, 0x63066CD9, 0xFA0F3D63, 0x8D080DF5,
    0x3B6E20C8, 0x4C69105E, 0xD56041E4, 0xA2677172, 0x3C03E4D1, 0x4B04D447, 0xD20D85FD, 0xA50AB56B,
    0x35B5A8FA, 0x42B2986C, 0xDBBBC9D6, 0xACBCF940, 0x32D86CE3, 0x45DF5C75, 0xDCD60DCF, 0xABD13D59,
    0x26D930AC, 0x51DE003A, 0xC8D75180, 0xBFD06116, 0x21B4F4B5, 0x56B3C423, 0xCFBA9599, 0xB8BDA50F,
    0x2802B89E, 0x5F058808, 0xC60CD9B2, 0xB10BE924, 0x2F6F7C87, 0x58684C11, 0xC1611DAB, 0xB6662D3D,
    0x76DC4190, 0x01DB7106, 0x98D220BC, 0xEFD5102A, 0x71B18589, 0x06B6B51F, 0x9FBFE4A5, 0xE8B8D433,
    0x7807C9A2, 0x0F00F934, 0x9609A88E, 0xE10E9818, 0x7F6A0DBB, 0x086D3D2D, 0x91646C97, 0xE6635C01,
    0x6B6B51F4, 0x1C6C6162, 0x856530D8, 0xF262004E, 0x6C0695ED, 0x1B01A57B, 0x8208F4C1, 0xF50FC457,
    0x65B0D9C6, 0x12B7E950, 0x8BBEB8EA, 0xFCB9887C, 0x62DD1DDF, 0x15DA2D49, 0x8CD37CF3, 0xFBD44C65,
    0x4DB26158, 0x3AB551CE, 0xA3BC0074, 0xD4BB30E2, 0x4ADFA541, 0x3DD895D7, 0xA4D1C46D, 0xD3D6F4FB,
    0x4369E96A, 0x346ED9FC, 0xAD678846, 0xDA60B8D0, 0x44042D73, 0x33031DE5, 0xAA0A4C5F, 0xDD0D7CC9,
    0x5005713C, 0x270241AA, 0xBE0B1010, 0xC90C2086, 0x5768B525, 0x206F85B3, 0xB966D409, 0xCE61E49F,
    0x5EDEF90E, 0x29D9C998, 0xB0D09822, 0xC7D7A8B4, 0x59B33D17, 0x2EB40D81, 0xB7BD5C3B, 0xC0BA6CAD,
    0xEDB88320, 0x9ABFB3B6, 0x03B6E20C, 0x74B1D29A, 0xEAD54739, 0x9DD277AF, 0x04DB2615, 0x73DC1683,
    0xE3630B12, 0x94643B84, 0x0D6D6A3E, 0x7A6A5AA8, 0xE40ECF0B, 0x9309FF9D, 0x0A00AE27, 0x7D079EB1,
    0xF00F9344, 0x8708A3D2, 0x1E01F268, 0x6906C2FE, 0xF762575D, 0x806567CB, 0x196C3671, 0x6E6B06E7,
    0xFED41B76, 0x89D32BE0, 0x10DA7A5A, 0x67DD4ACC, 0xF9B9DF6F, 0x8EBEEFF9, 0x17B7BE43, 0x60B08ED5,
    0xD6D6A3E8, 0xA1D1937E, 0x38D8C2C4, 0x4FDFF252, 0xD1BB67F1, 0xA6BC5767, 0x3FB506DD, 0x48B2364B,
    0xD80D2BDA, 0xAF0A1B4C, 0x36034AF6, 0x41047A60, 0xDF60EFC3, 0xA867DF55, 0x316E8EEF, 0x4669BE79,
    0xCB61B38C, 0xBC66831A, 0x256FD2A0, 0x5268E236, 0xCC0C7795, 0xBB0B4703, 0x220216B9, 0x5505262F,
    0xC5BA3BBE, 0xB2BD0B28, 0x2BB45A92, 0x5CB36A04, 0xC2D7FFA7, 0xB5D0CF31, 0x2CD99E8B, 0x5BDEAE1D,
    0x9B64C2B0, 0xEC63F226, 0x756AA39C, 0x026D930A, 0x9C0906A9, 0xEB0E363F, 0x72076785, 0x05005713,
    0x95BF4A82, 0xE2B87A14, 0x7BB12BAE, 0x0CB61B38, 0x92D28E9B, 0xE5D5BE0D, 0x7CDCEFB7, 0x0BDBDF21,
    0x86D3D2D4, 0xF1D4E242, 0x68DDB3F8, 0x1FDA836E, 0x81BE16CD, 0xF6B9265B, 0x6FB077E1, 0x18B74777,
    0x88085AE6, 0xFF0F6A70, 0x66063BCA, 0x11010B5C, 0x8F659EFF, 0xF862AE69, 0x616BFFD3, 0x166CCF45,
    0xA00AE278, 0xD70DD2EE, 0x4E048354, 0x3903B3C2, 0xA7672661, 0xD06016F7, 0x4969474D, 0x3E6E77DB,
    0xAED16A4A, 0xD9D65ADC, 0x40DF0B66, 0x37D83BF0, 0xA9BCAE53, 0xDEBB9EC5, 0x47B2CF7F, 0x30B5FFE9,
    0xBDBDF21C, 0xCABAC28A, 0x53B39330, 0x24B4A3A6, 0xBAD03605, 0xCDD70693, 0x54DE5729, 0x23D967BF,
    0xB3667A2E, 0xC4614AB8, 0x5D681B02, 0x2A6F2B94, 0xB40BBE37, 0xC30C8EA1, 0x5A05DF1B, 0x2D02EF8D
};

__forceinline DWORD HashString(LPCSTR str) {
    DWORD crc = 0xFFFFFFFF;
    while (*str) {
        crc = crc32_table[(crc ^ *str++) & 0xFF] ^ (crc >> 8);
    }
    return crc ^ 0xFFFFFFFF;
}
'''
        else:
            return f"// Hash algorithm '{algorithm}' not implemented in C++"
    
    @classmethod
    def get_common_api_hashes(cls, algorithm: str = "djb2") -> Dict[str, int]:
        """Get hashes for commonly used NT APIs"""
        common_apis = [
            "NtAllocateVirtualMemory",
            "NtProtectVirtualMemory",
            "NtWriteVirtualMemory",
            "NtReadVirtualMemory",
            "NtCreateThreadEx",
            "NtOpenProcess",
            "NtClose",
            "NtQueryInformationProcess",
            "NtQueryVirtualMemory",
            "NtFreeVirtualMemory",
            "NtResumeThread",
            "NtSuspendThread",
            "NtQueueApcThread",
            "NtWaitForSingleObject",
            "NtDelayExecution",
            "NtCreateSection",
            "NtMapViewOfSection",
            "NtUnmapViewOfSection",
            "NtCreateProcess",
            "NtCreateProcessEx",
            "NtTerminateProcess",
        ]
        return cls.generate_hash_table(common_apis, algorithm, skip_prefix=2)


# ============================================================================
# String Obfuscation
# ============================================================================

class StringObfuscator:
    """String obfuscation utilities"""
    
    @staticmethod
    def xor_string(s: str, key: int = 0x5A) -> bytes:
        """XOR obfuscate a string"""
        return bytes([ord(c) ^ key for c in s])
    
    @staticmethod
    def generate_xor_string_cpp(s: str, var_name: str, key: int = 0x5A) -> str:
        """Generate C++ code for XOR-obfuscated string"""
        obfuscated = StringObfuscator.xor_string(s, key)
        
        hex_bytes = ', '.join(f'0x{b:02X}' for b in obfuscated)
        
        code = f'''
// Obfuscated string ({var_name})
unsigned char {var_name}_enc[] = {{ {hex_bytes}, 0x00 }};
#define {var_name}_KEY 0x{key:02X}
#define {var_name}_LEN {len(s)}

__forceinline void Deobfuscate_{var_name}(char* out) {{
    for (int i = 0; i < {var_name}_LEN; i++) {{
        out[i] = {var_name}_enc[i] ^ {var_name}_KEY;
    }}
    out[{var_name}_LEN] = 0;
}}
'''
        return code
    
    @staticmethod
    def generate_stack_string_cpp(s: str, var_name: str) -> str:
        """Generate C++ code for stack-built string"""
        lines = [f"    // Stack string (obfuscated)"]
        lines.append(f"    char {var_name}[{len(s) + 1}];")
        
        for i, c in enumerate(s):
            lines.append(f"    {var_name}[{i}] = '{c}';")
        
        lines.append(f"    {var_name}[{len(s)}] = '\\0';")
        
        return '\n'.join(lines)
    
    @staticmethod
    def reverse_with_junk(s: str) -> bytes:
        """
        Reverse string and add junk characters (HookChain style)
        """
        result = bytearray()
        junk_chars = b'@#$%^&*()!-+=[]{}|;:,.<>?'
        
        for i, c in enumerate(reversed(s)):
            result.append(ord(c))
            # Add junk after some characters
            if i % 2 == 0 and i < len(s) - 1:
                result.append(junk_chars[i % len(junk_chars)])
        
        result.append(0)  # Null terminator
        return bytes(result)
    
    @staticmethod
    def generate_reversed_junk_cpp(s: str, var_name: str) -> str:
        """Generate C++ code for reversed+junk obfuscated string"""
        obfuscated = StringObfuscator.reverse_with_junk(s)
        hex_bytes = ', '.join(f'0x{b:02X}' for b in obfuscated)
        
        code = f'''
// Obfuscated (reversed+junk): {var_name}
unsigned char {var_name}_enc[] = {{ {hex_bytes} }};

__forceinline void Decode_{var_name}(char* out) {{
    int j = 0;
    int len = sizeof({var_name}_enc) - 1;
    for (int i = len - 1; i >= 0; i--) {{
        char c = {var_name}_enc[i];
        // Filter: only alphanumeric and underscore
        if ((c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z') || 
            (c >= 'a' && c <= 'z') || c == '_' || c == '.') {{
            out[j++] = c;
        }}
    }}
    out[j] = '\\0';
}}
'''
        return code


# ============================================================================
# Test
# ============================================================================

if __name__ == "__main__":
    engine = HashEngine()
    
    # Test hash algorithms
    test_name = "AllocateVirtualMemory"  # Without Nt prefix
    
    print("Hash Algorithm Comparison:")
    print(f"  Input: '{test_name}'")
    print(f"  DJB2:    0x{engine.djb2(test_name.encode()):016X}")
    print(f"  DJB2_32: 0x{engine.djb2_32(test_name.encode()):08X}")
    print(f"  CRC32:   0x{engine.crc32(test_name.encode()):08X}")
    print(f"  FNV-1a:  0x{engine.fnv1a_64(test_name.encode()):016X}")
    print(f"  XOR:     0x{engine.xor_hash(test_name.encode()):08X}")
    
    # Generate defines
    print("\n" + "="*60)
    print(engine.generate_cpp_defines([
        "NtAllocateVirtualMemory",
        "NtProtectVirtualMemory",
        "NtWriteVirtualMemory",
    ]))
    
    # Test string obfuscation
    print("\n" + "="*60)
    obf = StringObfuscator()
    print(obf.generate_xor_string_cpp("kernel32.dll", "g_Kernel32"))
    print(obf.generate_stack_string_cpp("ntdll.dll", "szNtdll"))